/**
 * 顶部导航配置
 * 从 HeaderBar.vue 的菜单逻辑中抽取，与 router/index.js 的路由 name 对齐
 */
export const navItems = [
  {
    key: 'home',
    icon: 'el-icon-s-home',
    titleKey: 'sidebar.home',
    routeName: 'home',
    requiresSuperAdmin: false,
    featureKey: undefined,
    children: undefined,
  },
  {
    key: 'roleConfig',
    icon: 'el-icon-user',
    titleKey: 'sidebar.roleConfig',
    routeName: 'RoleConfig',
    requiresSuperAdmin: false,
    featureKey: undefined,
    children: undefined,
  },
  {
    key: 'deviceManagement',
    icon: 'el-icon-mobile-phone',
    titleKey: 'sidebar.deviceManagement',
    routeName: 'DeviceManagement',
    requiresSuperAdmin: false,
    featureKey: undefined,
    children: undefined,
  },
  {
    key: 'voiceCloneManagement',
    icon: 'el-icon-microphone',
    titleKey: 'sidebar.voiceClone',
    routeName: 'VoiceCloneManagement',
    requiresSuperAdmin: false,
    featureKey: 'voiceClone',
    children: undefined,
  },
  {
    key: 'modelConfig',
    icon: 'el-icon-cpu',
    titleKey: 'sidebar.modelConfig',
    routeName: 'ModelConfig',
    requiresSuperAdmin: true,
    featureKey: undefined,
    children: undefined,
  },
  {
    key: 'knowledgeBaseManagement',
    icon: 'el-icon-notebook-2',
    titleKey: 'sidebar.knowledgeBase',
    routeName: 'KnowledgeBaseManagement',
    requiresSuperAdmin: false,
    featureKey: 'knowledgeBase',
    children: undefined,
  },
  {
    key: 'addressBookManagement',
    icon: 'el-icon-phone-outline',
    titleKey: 'sidebar.addressBook',
    routeName: 'AddressBookManagement',
    requiresSuperAdmin: false,
    featureKey: 'addressBook',
    children: undefined,
  },
  {
    key: 'systemManagement',
    icon: 'el-icon-setting',
    titleKey: 'sidebar.system',
    routeName: undefined,
    requiresSuperAdmin: true,
    featureKey: undefined,
    children: [
      {
        key: 'paramsManagement',
        icon: 'el-icon-s-tools',
        titleKey: 'sidebar.params',
        routeName: 'ParamsManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'userManagement',
        icon: 'el-icon-user-solid',
        titleKey: 'sidebar.users',
        routeName: 'UserManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'otaManagement',
        icon: 'el-icon-refresh',
        titleKey: 'sidebar.ota',
        routeName: 'OtaManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'dictManagement',
        icon: 'el-icon-reading',
        titleKey: 'sidebar.dict',
        routeName: 'DictManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'providerManagement',
        icon: 'el-icon-office-building',
        titleKey: 'sidebar.provider',
        routeName: 'ProviderManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'agentTemplateManagement',
        icon: 'el-icon-s-custom',
        titleKey: 'sidebar.roleTemplate',
        routeName: 'AgentTemplateManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'replacementWordManagement',
        icon: 'el-icon-refresh-left',
        titleKey: 'sidebar.replacement',
        routeName: 'ReplacementWordManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'serverSideManagement',
        icon: 'el-icon-s-platform',
        titleKey: 'sidebar.server',
        routeName: 'ServerSideManager',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
      {
        key: 'featureManagement',
        icon: 'el-icon-s-operation',
        titleKey: 'sidebar.feature',
        routeName: 'FeatureManagement',
        requiresSuperAdmin: true,
        featureKey: undefined,
        children: undefined,
      },
    ],
  },
];

export default navItems;
